### PR TITLE
Fix include path handling in nested includes

### PR DESCRIPTION
**Pull request by kyle-figure**
* Adds new keyword `include_relative` to allow nested includes to resolve paths relatively
* Adds nested include test
* Removes deprecated pybind11-stubgen CLI arguments

### CODE REVIEW

**Comment by kyle-figure** [comment]
@michael-projectx Could you take a look at the error log on this PR when you get a chance? I see the following error:
```
pybind11-stubgen: error: unrecognized arguments: --root-module-suffix --no-setup-py flexi_cfg
```

**Comment by miker2** [comment]
@kyle-figure can you instead add a new `include_relative` tag instead of modifying the existing `include` tag? I have an existing project that uses this library and it looks like the config passing is broken with this change.

**Comment by miker2** [comment]
Also, can you update the `README.md` to reflect the changes?

**Comment by kyle-figure** [comment]
@miker2 I've reverted the change to the include keyword and added a `include_relative` keyword

**Review by michael-projectx — APPROVED** [review]

**Pull request merged**
